name: Upload Python Package



on:
  release:
    types: [published]

  push:
    branches:
      - main
      - develop
      - master


permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Debug - List files in working directory
      run: ls -la

    - name: Debug - Show requirements.txt content
      run: cat requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # This line installs all dependencies listed in requirements.txt

    - name: Check installed packages
      run: pip list

    - name: Run tests
      run: pytest tests/

    - name: Build package
      if: success()
      run: python -m build

#    - name: Publish package
#      if: success()
#      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
